services:
  - type: web
    name: fastapi-a2l-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./a2l.db
    plan: free
